apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-js
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-js
  template:
    metadata:
      labels:
        app: node-js
    spec:
      containers:
      - name: node-js
        image: cloud1409/node-js-sample:1.0
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: nodejs-storage
          mountPath: /usr/src/app/data
      volumes:
      - name: nodejs-storage
        persistentVolumeClaim:
          claimName: node-js-pvc
